INSERT INTO aseguradoras VALUES('GNP');
INSERT INTO aseguradoras VALUES('AXA');
INSERT INTO aseguradoras VALUES('AARCO');
INSERT INTO aseguradoras VALUES('ZURICH');
INSERT INTO aseguradoras VALUES('METLIFE');
INSERT INTO aseguradoras VALUES('CHUBB');
INSERT INTO aseguradoras VALUES('PLAN SEGURO');

INSERT INTO ramos VALUES('AUTOS');
INSERT INTO ramos VALUES('HOGAR');
INSERT INTO ramos VALUES('TRANSPORTE');
INSERT INTO ramos VALUES('EMPRESARIAL');
INSERT INTO ramos VALUES('RESPONSABILIDAD CIVIL');
INSERT INTO ramos VALUES('GASTOS MEDICOS');
INSERT INTO ramos VALUES('ACCIDENTES PERSONALES');
INSERT INTO ramos VALUES('VIDA');
INSERT INTO ramos VALUES('INVERSION');

INSERT INTO estados VALUES('Aguascalientes');
INSERT INTO estados VALUES('Baja California');
INSERT INTO estados VALUES('Baja California Sur');
INSERT INTO estados VALUES('Campeche');
INSERT INTO estados VALUES('Chiapas');
INSERT INTO estados VALUES('Chihuahua');
INSERT INTO estados VALUES('Ciudad de México');
INSERT INTO estados VALUES('Coahuila');
INSERT INTO estados VALUES('Colima');
INSERT INTO estados VALUES('Durango');
INSERT INTO estados VALUES('Estado de México');
INSERT INTO estados VALUES('Guanajuato');
INSERT INTO estados VALUES('Guerrero');
INSERT INTO estados VALUES('Hidalgo');
INSERT INTO estados VALUES('Jalisco');
INSERT INTO estados VALUES('Michoacán');
INSERT INTO estados VALUES('Morelos');
INSERT INTO estados VALUES('Nayarit');
INSERT INTO estados VALUES('Nuevo León');
INSERT INTO estados VALUES('Oaxaca');
INSERT INTO estados VALUES('Puebla');
INSERT INTO estados VALUES('Querétaro');
INSERT INTO estados VALUES('Quintana Roo');
INSERT INTO estados VALUES('San Luis Potosí');
INSERT INTO estados VALUES('Sinaloa');
INSERT INTO estados VALUES('Sonora');
INSERT INTO estados VALUES('Tabasco');
INSERT INTO estados VALUES('Tamaulipas');
INSERT INTO estados VALUES('Tlaxcala');
INSERT INTO estados VALUES('Veracruz');
INSERT INTO estados VALUES('Yucatán');
INSERT INTO estados VALUES('Zacatecas');